custom_db:
    db_domain: 10.0.1.7
    db_username: root
    db_passwd: my_passwd
    db_schema: test

redis:
    redis_domain: 10.0.1.2
    redis_passwd: 123456

hello:
    num_config: [yaml-test]
    name_config: [powered, by, yaml-test]


