// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#include "test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace test {
class Example1_EmbeddedMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Example1_EmbeddedMessage>
      _instance;
} _Example1_EmbeddedMessage_default_instance_;
class Example1DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Example1>
      _instance;
} _Example1_default_instance_;
}  // namespace test
namespace protobuf_test_2eproto {
void InitDefaultsExample1_EmbeddedMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::test::_Example1_EmbeddedMessage_default_instance_;
    new (ptr) ::test::Example1_EmbeddedMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::Example1_EmbeddedMessage::InitAsDefaultInstance();
}

void InitDefaultsExample1_EmbeddedMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsExample1_EmbeddedMessageImpl);
}

void InitDefaultsExample1Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_test_2eproto::InitDefaultsExample1_EmbeddedMessage();
  {
    void* ptr = &::test::_Example1_default_instance_;
    new (ptr) ::test::Example1();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::test::Example1::InitAsDefaultInstance();
}

void InitDefaultsExample1() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsExample1Impl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1_EmbeddedMessage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1_EmbeddedMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1_EmbeddedMessage, int32val_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1_EmbeddedMessage, stringval_),
  1,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, stringval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, bytesval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, embeddedexample1_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, repeatedint32val_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::test::Example1, repeatedstringval_),
  0,
  1,
  2,
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::test::Example1_EmbeddedMessage)},
  { 9, 19, sizeof(::test::Example1)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_Example1_EmbeddedMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::test::_Example1_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "test.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ntest.proto\022\004test\"\326\001\n\010Example1\022\021\n\tstrin"
      "gVal\030\001 \001(\t\022\020\n\010bytesVal\030\002 \001(\014\0228\n\020embedded"
      "Example1\030\003 \001(\0132\036.test.Example1.EmbeddedM"
      "essage\022\030\n\020repeatedInt32Val\030\004 \003(\005\022\031\n\021repe"
      "atedStringVal\030\005 \003(\t\0326\n\017EmbeddedMessage\022\020"
      "\n\010int32Val\030\001 \001(\005\022\021\n\tstringVal\030\002 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 235);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_test_2eproto
namespace test {

// ===================================================================

void Example1_EmbeddedMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Example1_EmbeddedMessage::kInt32ValFieldNumber;
const int Example1_EmbeddedMessage::kStringValFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Example1_EmbeddedMessage::Example1_EmbeddedMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_test_2eproto::InitDefaultsExample1_EmbeddedMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.Example1.EmbeddedMessage)
}
Example1_EmbeddedMessage::Example1_EmbeddedMessage(const Example1_EmbeddedMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_stringval()) {
    stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
  }
  int32val_ = from.int32val_;
  // @@protoc_insertion_point(copy_constructor:test.Example1.EmbeddedMessage)
}

void Example1_EmbeddedMessage::SharedCtor() {
  _cached_size_ = 0;
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  int32val_ = 0;
}

Example1_EmbeddedMessage::~Example1_EmbeddedMessage() {
  // @@protoc_insertion_point(destructor:test.Example1.EmbeddedMessage)
  SharedDtor();
}

void Example1_EmbeddedMessage::SharedDtor() {
  stringval_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Example1_EmbeddedMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Example1_EmbeddedMessage::descriptor() {
  ::protobuf_test_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Example1_EmbeddedMessage& Example1_EmbeddedMessage::default_instance() {
  ::protobuf_test_2eproto::InitDefaultsExample1_EmbeddedMessage();
  return *internal_default_instance();
}

Example1_EmbeddedMessage* Example1_EmbeddedMessage::New(::google::protobuf::Arena* arena) const {
  Example1_EmbeddedMessage* n = new Example1_EmbeddedMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Example1_EmbeddedMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:test.Example1.EmbeddedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    GOOGLE_DCHECK(!stringval_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*stringval_.UnsafeRawStringPointer())->clear();
  }
  int32val_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Example1_EmbeddedMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.Example1.EmbeddedMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 int32Val = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_int32val();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &int32val_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string stringVal = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringval()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->stringval().data(), static_cast<int>(this->stringval().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "test.Example1.EmbeddedMessage.stringVal");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.Example1.EmbeddedMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.Example1.EmbeddedMessage)
  return false;
#undef DO_
}

void Example1_EmbeddedMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.Example1.EmbeddedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 int32Val = 1;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->int32val(), output);
  }

  // optional string stringVal = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Example1.EmbeddedMessage.stringVal");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->stringval(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:test.Example1.EmbeddedMessage)
}

::google::protobuf::uint8* Example1_EmbeddedMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.Example1.EmbeddedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional int32 int32Val = 1;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->int32val(), target);
  }

  // optional string stringVal = 2;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Example1.EmbeddedMessage.stringVal");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->stringval(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.Example1.EmbeddedMessage)
  return target;
}

size_t Example1_EmbeddedMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.Example1.EmbeddedMessage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string stringVal = 2;
    if (has_stringval()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->stringval());
    }

    // optional int32 int32Val = 1;
    if (has_int32val()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->int32val());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Example1_EmbeddedMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.Example1.EmbeddedMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const Example1_EmbeddedMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Example1_EmbeddedMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.Example1.EmbeddedMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.Example1.EmbeddedMessage)
    MergeFrom(*source);
  }
}

void Example1_EmbeddedMessage::MergeFrom(const Example1_EmbeddedMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.Example1.EmbeddedMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_stringval();
      stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
    }
    if (cached_has_bits & 0x00000002u) {
      int32val_ = from.int32val_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Example1_EmbeddedMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.Example1.EmbeddedMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Example1_EmbeddedMessage::CopyFrom(const Example1_EmbeddedMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.Example1.EmbeddedMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example1_EmbeddedMessage::IsInitialized() const {
  return true;
}

void Example1_EmbeddedMessage::Swap(Example1_EmbeddedMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Example1_EmbeddedMessage::InternalSwap(Example1_EmbeddedMessage* other) {
  using std::swap;
  stringval_.Swap(&other->stringval_);
  swap(int32val_, other->int32val_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Example1_EmbeddedMessage::GetMetadata() const {
  protobuf_test_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Example1::InitAsDefaultInstance() {
  ::test::_Example1_default_instance_._instance.get_mutable()->embeddedexample1_ = const_cast< ::test::Example1_EmbeddedMessage*>(
      ::test::Example1_EmbeddedMessage::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Example1::kStringValFieldNumber;
const int Example1::kBytesValFieldNumber;
const int Example1::kEmbeddedExample1FieldNumber;
const int Example1::kRepeatedInt32ValFieldNumber;
const int Example1::kRepeatedStringValFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Example1::Example1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_test_2eproto::InitDefaultsExample1();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:test.Example1)
}
Example1::Example1(const Example1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      repeatedint32val_(from.repeatedint32val_),
      repeatedstringval_(from.repeatedstringval_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_stringval()) {
    stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
  }
  bytesval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_bytesval()) {
    bytesval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytesval_);
  }
  if (from.has_embeddedexample1()) {
    embeddedexample1_ = new ::test::Example1_EmbeddedMessage(*from.embeddedexample1_);
  } else {
    embeddedexample1_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:test.Example1)
}

void Example1::SharedCtor() {
  _cached_size_ = 0;
  stringval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytesval_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  embeddedexample1_ = NULL;
}

Example1::~Example1() {
  // @@protoc_insertion_point(destructor:test.Example1)
  SharedDtor();
}

void Example1::SharedDtor() {
  stringval_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bytesval_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete embeddedexample1_;
}

void Example1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Example1::descriptor() {
  ::protobuf_test_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Example1& Example1::default_instance() {
  ::protobuf_test_2eproto::InitDefaultsExample1();
  return *internal_default_instance();
}

Example1* Example1::New(::google::protobuf::Arena* arena) const {
  Example1* n = new Example1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Example1::Clear() {
// @@protoc_insertion_point(message_clear_start:test.Example1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  repeatedint32val_.Clear();
  repeatedstringval_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!stringval_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*stringval_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!bytesval_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*bytesval_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(embeddedexample1_ != NULL);
      embeddedexample1_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Example1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:test.Example1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string stringVal = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringval()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->stringval().data(), static_cast<int>(this->stringval().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "test.Example1.stringVal");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bytes bytesVal = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytesval()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .test.Example1.EmbeddedMessage embeddedExample1 = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_embeddedexample1()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 repeatedInt32Val = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 32u, input, this->mutable_repeatedint32val())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_repeatedint32val())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string repeatedStringVal = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_repeatedstringval()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->repeatedstringval(this->repeatedstringval_size() - 1).data(),
            static_cast<int>(this->repeatedstringval(this->repeatedstringval_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "test.Example1.repeatedStringVal");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:test.Example1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:test.Example1)
  return false;
#undef DO_
}

void Example1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:test.Example1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string stringVal = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Example1.stringVal");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->stringval(), output);
  }

  // optional bytes bytesVal = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->bytesval(), output);
  }

  // optional .test.Example1.EmbeddedMessage embeddedExample1 = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->embeddedexample1_, output);
  }

  // repeated int32 repeatedInt32Val = 4;
  for (int i = 0, n = this->repeatedint32val_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      4, this->repeatedint32val(i), output);
  }

  // repeated string repeatedStringVal = 5;
  for (int i = 0, n = this->repeatedstringval_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->repeatedstringval(i).data(), static_cast<int>(this->repeatedstringval(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Example1.repeatedStringVal");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->repeatedstringval(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:test.Example1)
}

::google::protobuf::uint8* Example1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:test.Example1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string stringVal = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->stringval().data(), static_cast<int>(this->stringval().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Example1.stringVal");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->stringval(), target);
  }

  // optional bytes bytesVal = 2;
  if (cached_has_bits & 0x00000002u) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->bytesval(), target);
  }

  // optional .test.Example1.EmbeddedMessage embeddedExample1 = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->embeddedexample1_, deterministic, target);
  }

  // repeated int32 repeatedInt32Val = 4;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteInt32ToArray(4, this->repeatedint32val_, target);

  // repeated string repeatedStringVal = 5;
  for (int i = 0, n = this->repeatedstringval_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->repeatedstringval(i).data(), static_cast<int>(this->repeatedstringval(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "test.Example1.repeatedStringVal");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->repeatedstringval(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:test.Example1)
  return target;
}

size_t Example1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:test.Example1)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated int32 repeatedInt32Val = 4;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->repeatedint32val_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->repeatedint32val_size());
    total_size += data_size;
  }

  // repeated string repeatedStringVal = 5;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->repeatedstringval_size());
  for (int i = 0, n = this->repeatedstringval_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->repeatedstringval(i));
  }

  if (_has_bits_[0 / 32] & 7u) {
    // optional string stringVal = 1;
    if (has_stringval()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->stringval());
    }

    // optional bytes bytesVal = 2;
    if (has_bytesval()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->bytesval());
    }

    // optional .test.Example1.EmbeddedMessage embeddedExample1 = 3;
    if (has_embeddedexample1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *this->embeddedexample1_);
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Example1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:test.Example1)
  GOOGLE_DCHECK_NE(&from, this);
  const Example1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Example1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:test.Example1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:test.Example1)
    MergeFrom(*source);
  }
}

void Example1::MergeFrom(const Example1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:test.Example1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  repeatedint32val_.MergeFrom(from.repeatedint32val_);
  repeatedstringval_.MergeFrom(from.repeatedstringval_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_stringval();
      stringval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringval_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_bytesval();
      bytesval_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytesval_);
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_embeddedexample1()->::test::Example1_EmbeddedMessage::MergeFrom(from.embeddedexample1());
    }
  }
}

void Example1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:test.Example1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Example1::CopyFrom(const Example1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.Example1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Example1::IsInitialized() const {
  return true;
}

void Example1::Swap(Example1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Example1::InternalSwap(Example1* other) {
  using std::swap;
  repeatedint32val_.InternalSwap(&other->repeatedint32val_);
  repeatedstringval_.InternalSwap(&other->repeatedstringval_);
  stringval_.Swap(&other->stringval_);
  bytesval_.Swap(&other->bytesval_);
  swap(embeddedexample1_, other->embeddedexample1_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Example1::GetMetadata() const {
  protobuf_test_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_test_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace test

// @@protoc_insertion_point(global_scope)
